### PR TITLE
fix: create app script not building apps correctly

### LINKED ISSUE #434: Create App Issues
## Summary

- Tests fail for projects made running the create app script
- When using the react flag, no react related files or directories are created

## Steps To Reproduce The Bug

1. Run the create app with either `--api` or `--web-app`
2. Run tests
3. See tests fail
4. Removal all files and create a react project
5. See no react related files are created

## Expected Behavior

Tests should pass and the related react files for react projects should be created and work properly

## Suggested Solution(s)

- Tests: just need to be fixed
- React: I'm guessing within the logic of the script, the `if (wantsReact)` never passes, so maybe the var `wantsReact` is false eg not parsing the cli flag correctly

### PR DESCRIPTION
**Pull request by crookse**
Closes #434 

**Description**

* Fixes create app script from failing
* Fixes web app from not loading
* Builds two types of tests: one for APIs and one for Web Apps
* Removes tests from being created for Vue and React apps
* Points Create App Script README section to https://drash.land/drash tutorial on Create App Script

### CODE REVIEW

File: console/create_app/tests/resources/home_resource_test_api.ts [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+      {
+        message: "GET request received!",
+      },
+    );
+
+    // Stop the server
+    await server.close();
+  },
+  sanitizeResources: false,
+  sanitizeOps: false,
```
Comment (ebebbington) [inline console/create_app/tests/resources/home_resource_test_api.ts:35]: does removing this cause issues? hoping we should avoid this especially for user facing stuff

File: console/create_app/tests/resources/home_resource_test_api.ts [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+      {
+        message: "POST method not implemented.",
+      },
+    );
+
+    // Stop the server
+    await server.close();
+  },
+  sanitizeResources: false,
+  sanitizeOps: false,
```
Comment (ebebbington) [inline console/create_app/tests/resources/home_resource_test_api.ts:62]: same as above

File: console/create_app/tests/resources/home_resource_test_api.ts [hunk 3]
```diff
@@ -0,0 +1,119 @@
...
+      {
+        message: "PUT method not implemented.",
+      },
+    );
+
+    // Stop the server
+    await server.close();
+  },
+  sanitizeResources: false,
+  sanitizeOps: false,
```
Comment (ebebbington) [inline console/create_app/tests/resources/home_resource_test_api.ts:89]: same as above

File: console/create_app/tests/resources/home_resource_test_api.ts [hunk 4]
```diff
@@ -0,0 +1,119 @@
...
+      {
+        message: "DELETE method not implemented.",
+      },
+    );
+
+    // Stop the server
+    await server.close();
+  },
+  sanitizeResources: false,
+  sanitizeOps: false,
```
Comment (ebebbington) [inline console/create_app/tests/resources/home_resource_test_api.ts:116]: same as above

File: console/create_app/tests/resources/home_resource_test_web_app.ts [hunk 5]
```diff
@@ -0,0 +1,111 @@
...
+    assertEquals(
+      await response.text(),
+      '<!DOCTYPE html>\n<html>\n    <head>\n        <meta charset="utf-8">\n        <meta name="viewport" content="width=device-width, initial-scale=1">\n        <script src="/public/js/index.js"></script>\n        <link rel="stylesheet" href="/public/css/index.css">\n        <title>Drash - Create App</title>\n    </head>\n    <body>\n        <main>\n            <h1>Welcome</h1>\n            <p>Welcome to your new application, start building something great with Drash!</p>\n        </main>\n    </body>\n</html>',
+    );
+
+    // Stop the server
+    await server.close();
+  },
+  sanitizeResources: false,
+  sanitizeOps: false,
```
Comment (ebebbington) [inline console/create_app/tests/resources/home_resource_test_web_app.ts:33]: same as above

File: console/create_app/tests/resources/home_resource_test_web_app.ts [hunk 6]
```diff
@@ -0,0 +1,111 @@
...
+    assertEquals(
+      await response.text(),
+      "POST method not implemented.",
+    );
+
+    // Stop the server
+    await server.close();
+  },
+  sanitizeResources: false,
+  sanitizeOps: false,
```
Comment (ebebbington) [inline console/create_app/tests/resources/home_resource_test_web_app.ts:58]: same as above

File: console/create_app/tests/resources/home_resource_test_web_app.ts [hunk 7]
```diff
@@ -0,0 +1,111 @@
...
+    assertEquals(
+      await response.text(),
+      "PUT method not implemented.",
+    );
+
+    // Stop the server
+    await server.close();
+  },
+  sanitizeResources: false,
+  sanitizeOps: false,
```
Comment (ebebbington) [inline console/create_app/tests/resources/home_resource_test_web_app.ts:83]: same as above

File: console/create_app/tests/resources/home_resource_test_web_app.ts [hunk 8]
```diff
@@ -0,0 +1,111 @@
...
+    assertEquals(
+      await response.text(),
+      "DELETE method not implemented.",
+    );
+
+    // Stop the server
+    await server.close();
+  },
+  sanitizeResources: false,
+  sanitizeOps: false,
```
Comment (ebebbington) [inline console/create_app/tests/resources/home_resource_test_web_app.ts:108]: same as above

File: tests/cli/create_app_test_local.ts [hunk 9]
```diff
@@ -367,146 +368,133 @@ Rhum.testPlan("create_app_test.ts", () => {
...
+    Rhum.testCase("home_resource.ts exists", async () => {
+      // home_resource.ts
+      Rhum.asserts.assertEquals(
+        await fileExists(testCaseTmpDirName + "/resources/home_resource.ts"),
+        true,
+      );
+    });
+
+    Rhum.testCase("img.ts exists", async () => {
+      // public/img.ts
```
Comment (ebebbington) [inline tests/cli/create_app_test_local.ts:440]: `img` is a directory remember ;)

**Review by ebebbington — CHANGES_REQUESTED** [review]
Just a couple things noted, most are similar comments

Was the react stuff fixed too? Couldn't see any code changes related to react

I'm thinking maybe we also have a test case to run the tests of the api and web app? to ensure they work?

File: console/create_app/tests/resources/home_resource_test_api.ts (hunk 1 above)
Comment (crookse) [reply console/create_app/tests/resources/home_resource_test_api.ts:35]: yea it causes leaking

File: console/create_app/tests/resources/home_resource_test_api.ts (hunk 2 above)
Comment (crookse) [reply console/create_app/tests/resources/home_resource_test_api.ts:62]: removing this causes leaking

File: console/create_app/tests/resources/home_resource_test_api.ts (hunk 3 above)
Comment (crookse) [reply console/create_app/tests/resources/home_resource_test_api.ts:89]: removing this causes leaking

File: console/create_app/tests/resources/home_resource_test_web_app.ts (hunk 5 above)
Comment (crookse) [reply console/create_app/tests/resources/home_resource_test_web_app.ts:33]: removing this causes leaking

File: console/create_app/tests/resources/home_resource_test_web_app.ts (hunk 6 above)
Comment (crookse) [reply console/create_app/tests/resources/home_resource_test_web_app.ts:58]: removing this causes leaking

File: console/create_app/tests/resources/home_resource_test_web_app.ts (hunk 7 above)
Comment (crookse) [reply console/create_app/tests/resources/home_resource_test_web_app.ts:83]: removing this causes leaking

File: console/create_app/tests/resources/home_resource_test_web_app.ts (hunk 8 above)
Comment (crookse) [reply console/create_app/tests/resources/home_resource_test_web_app.ts:108]: removing this causes leaking

**Comment by crookse** [comment]
> Just a couple things noted, most are similar comments
> 
> Was the react stuff fixed too? Couldn't see any code changes related to react
> 
> I'm thinking maybe we also have a test case to run the tests of the api and web app? to ensure they work?

the react app was working just fine when i went through the process of creating one

File: tests/cli/create_app_test_local.ts (hunk 9 above)
Comment (crookse) [reply tests/cli/create_app_test_local.ts]: 5f8f0d0

File: console/create_app/tests/resources/home_resource_test_api.ts (hunk 1 above)
Comment (ebebbington) [reply console/create_app/tests/resources/home_resource_test_api.ts:35]: Because we import the server from app.ts which subsequently starts the main server also and never gets closed

I think it might be best we. create the server object within the test, or abstract the logic that creates the server object? then for example we import that into app.ts and. the test or something

FYI this comment applies to. all the others that are similar, i'll close all of them when this comment addressed

Comment (crookse) [reply console/create_app/tests/resources/home_resource_test_api.ts]: 8de4407 (create server_app.ts and server_web_app.ts. also export them)
5124467 (tests failed in the commit above. this commit fixes the tests)

**Comment by crookse** [comment]
ready for review. i also fixed the react note (769dd1f)

**Review by ebebbington — APPROVED** [review]
Nice one!
