### PR TITLE
[issue-#253-create-app-not-working] fetch files instead of copying lo…

### LINKED ISSUE #253: [create_app.ts] Uncaught NotFound: File not found
**Describe the bug**
Error being thrown when running the create_app.ts script

**To Reproduce**

```
deno run --allow-run --allow-read --allow-write https://deno.land/x/drash@v1.0.5/create_app.ts --api
```

**Expected behavior**

API project (with all directories) exists

**Screenshots**

Screen Shot 2020-06-14 at 07 55 14

### PR DESCRIPTION
**Pull request by crookse**
Fixes #253

### CODE REVIEW

File: tests/cli/create_app_test.ts [hunk 1]
```diff
@@ -134,6 +134,7 @@ members.test("create_app_test.ts | Script creates an API project with the --api
       "run",
       "--allow-read",
       "--allow-write",
+      "--allow-net",
```
Comment (saragee3) [inline tests/cli/create_app_test.ts:137]: is `--allow-all` an option?

Comment (crookse) [reply tests/cli/create_app_test.ts:137]: Yea
